### ISSUE TITLE
Bug in <helper>: display_remaining_budget() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by AMShek** [vegechick510/DollarBot#10]
ERROR:root:display_remaining_budget() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/workspaces/DollarBot/code/add.py", line 135, in post_amount_input
    helper.display_remaining_budget(message, bot, selected_category)
TypeError: display_remaining_budget() takes 2 positional arguments but 3 were given

**Comment by AMShek** [comment]
this issue appeared before, but I still got the error report

**Comment by xiantinglu** [comment]
Has this issue been solved?

**Comment by AMShek** [comment]
> Has this issue been solved?

Yes! I refactor that function, and now everything looks fine.
