### ISSUE TITLE
test cases failed in test_add.py

### ISSUE THREAD

**Issue by xiantinglu** [vegechick510/DollarBot#15]
test cases failed in test_add.py:

FAILED test/test_add.py::test_add_user_record_with_currency_conversion[1200-JPY-Shopping-7.82] - assert 7.84 == 7.82

**Comment by xianglan010** [comment]
real time currency?

**Comment by xiantinglu** [comment]
That seems to be the case.

**Comment by xiantinglu** [comment]
solved https://github.com/vegechick510/DollarBot/commit/102a7c831c2201f3e1d725fa7ed4d27ebb0d0f2c
