### ISSUE TITLE
Bug in updating budget limit; argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by xiantinglu** [vegechick510/DollarBot#7]
Oh no! argument of type 'NoneType' is not iterable

Traceback (most recent call last):
  File "/XXX/DollarBot/code/budget_limit.py", line 106, in post_budget_limit_input
    if str(chat_id) not in user_list:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by AMShek** [comment]
Maybe you can return an empty dictionary, rather than 'None', in this case to fix this issue
